version: "3.7"

services:
  postgres:
    image: postgres:12.2
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: redirect
      POSTGRES_USER: redirect
      POSTGRES_DB: redirect
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data